<a href="https://colab.research.google.com/github/Aswin1655/23CSBTB29/blob/main/1st_aiml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,9,5,8])
print(np.sort(arr))

[1 5 8 9]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
sum_of_array = np.sum(arr)
print(sum_of_array)

15


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=(a+b)
print(c)

[ 7  9 11 13 15]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=(a*b)
print(c)

[ 6 14 24 36 50]


In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=(a/b)
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=(a-b)
print(c)

[-5 -5 -5 -5 -5]
